# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: "windows-latest"

variables:
  Env: "Dev"
  BuildConfiguration: "release"
  BuildPlatform: "Any Cpu"
steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Sonar service connection'
      organization: 'smkr-devops'
      scannerMode: 'MSBuild'
      projectKey: 'smkr-devops'
      projectName: 'dotnet-smkr-project'
  - task: NuGetToolInstaller@1
    displayName: "Nuget version"
    inputs:
      versionSpec: '4.9.1'
  - task: NuGetCommand@2
    displayName: "Nuget restore"
    inputs:
      command: 'restore'
      restoreSolution: 'Dotnet/FlowerShop.sln'
      feedsToUse: 'select'
  - task: VSBuild@1
    displayName: "visual studio build"
    inputs:
      solution: 'Dotnet/FlowerShop.sln'
      vsVersion: '16.0'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
  - task: SonarCloudAnalyze@1
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  - task: DownloadBuildArtifacts@1
    inputs:
      buildType: 'current'
      downloadType: 'single'
      downloadPath: '$(System.ArtifactsDirectory)'
  - task: AzureRmWebAppDeployment@4
    displayName: "azure app services"
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'MANI''s AZURE(12c0d075-059f-4523-8432-5eee63b9ac55)'
      appType: 'webApp'
      WebAppName: 'dotnet-project-webapp'
      packageForLinux: '$(System.DefaultWorkingDirectory)'