trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

- stage: Release
  displayName: Release
  jobs:
  - deployment:
    displayName: Release

    environment: Release
    strategy:
      runOnce:
        deploy:
          steps:               

            
            - task: DownloadBuildArtifacts@1
              displayName: Copy artifacts to release directory
              inputs:
                buildType: 'current'
                downloadType: 'specific'
                downloadPath: '$(System.ArtifactsDirectory)'
            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'MANI''s AZURE (12c0d075-059f-4523-8432-5eee63b9ac55)'
                appType: 'webApp'
                appName: 'DOTNET-WEBAPP-DEV'
                package: '$(System.DefaultWorkingDirectory)'
                deploymentMethod: 'auto'